---
title: "Stop Wine-ing"
author: "Hosea"
date: "22/02/2022"
output: html_document
---

Packages and data and so on and so on 

```{r}
library(tidyverse)
library(ggplot2)
library(rpart)
library(rpart.plot)
library(caret)
library(tidyr)

dir <- "/Users/hosea/Documents/R/edX-Datascience-Harvard/Capstone/Wine/WineQT.csv"
df <- read.csv(dir)

vars <- colnames(df)
# df <- df %>% mutate(quality = as.factor(quality)) 

head(df)
head(df)
```

Preliminary analysis and so on and so on 

```{r}
#Histogram of ratings
ggplot(data = df) + geom_histogram(aes(x=quality)) 

#Global measurement vs rating
dftall <- df %>% gather(variable, measurement ,fixed.acidity:alcohol) 
ggplot(data = dftall) + geom_point(aes(x= measurement,y=quality, col = variable)) 


#Summary plot
meanVars <- df %>% group_by(quality)  %>% 
  summarise_if(is.numeric, mean)

#Plot each variable
ggplot(data = meanVars) + geom_point(aes(x=fixed.acidity,y=quality))
ggplot(data = meanVars) + geom_point(aes(x=volatile.acidity,y=quality))
ggplot(data = meanVars) + geom_point(aes(x=citric.acid,y=quality))
ggplot(data = meanVars) + geom_point(aes(x=residual.sugar,y=quality))
ggplot(data = meanVars) + geom_point(aes(x=chlorides,y=quality))
ggplot(data = meanVars) + geom_point(aes(x=free.sulfur.dioxide,y=quality))
ggplot(data = meanVars) + geom_point(aes(x=total.sulfur.dioxide,y=quality))
ggplot(data = meanVars) + geom_point(aes(x=density,y=quality))
ggplot(data = meanVars) + geom_point(aes(x=pH,y=quality))
ggplot(data = meanVars) + geom_point(aes(x=sulphates,y=quality))
ggplot(data = meanVars) + geom_point(aes(x=alcohol,y=quality))


df %>%
  mutate(qlty = as.factor(quality)) %>%
  ggplot(aes(y = fixed.acidity, group = qlty)) +
  geom_boxplot()
```


Linear - volatile acidity, citric acid, chlorides

```{r}

lmodel <- lm(quality ~  volatile.acidity + chlorides + total.sulfur.dioxide + sulphates + alcohol + pH + sulphates + total.sulfur.dioxide , Hess = T, data = df) 
summary(lmodel)
plot(lmodel)
```




